BUMP: all packages bumped to latest + switched mold for lld + added --cfg erase_components flag
mold was causing recursion overflow errors:
 error: queries overflow the depth limit!
104.3   |
104.3   = help: consider increasing the recursion limit by adding a
`#![recursion_limit = "256"]` attribute to your crate
(`leptos_website_maj`)
the recursion limit was already at 256 so the solution for now seems to
be to switch mold for lld and set RUSTFLAGS="--cfg erase_components".
more:
https://github.com/leptos-rs/leptos/issues/3433#issuecomment-2569314319